#pragma once

#include <unordered_map>
#include <functional>


class DefaultViewModelSequence {
private:
	std::unordered_map<uint64_t, int> activityMap_;

	static uint64_t makeKey(int weaponID, int sequence) {
        return ((static_cast<uint64_t>(weaponID) << 32) |  static_cast<uint64_t>(sequence));
    }

public:
	DefaultViewModelSequence() {
		initDefaultModelSequence();
	}

	void Add(int weaponID, int sequence, int activity) {
        activityMap_[makeKey(weaponID, sequence)] = activity;
    }

	int Get(int weaponID, int sequence) const {
        auto key = makeKey(weaponID, sequence);
        auto it = activityMap_.find(key);
        if (it != activityMap_.end()) {
            return it->second;
        }
        return -1;
    }

	void initDefaultModelSequence() {
		//pisitol
		Add(NECOLA_WEAPON_PISTOL, 3, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_PISTOL, 5, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_PISTOL, 7, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_PISTOL, 9, ACT_VM_RELOAD_EMPTY_LAYER);
		// Add(NECOLA_WEAPON_PISTOL, 11, ACT_VM_DRYFIRE);
		Add(NECOLA_WEAPON_PISTOL, 13, ACT_VM_MELEE_LAYER);

		//pisitol_dual
		Add(NECOLA_WEAPON_PISTOL_DUAL, 3, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_PISTOL_DUAL, 5, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_PISTOL_DUAL, 7, ACT_VM_SECONDARYATTACK_LAYER);
		Add(NECOLA_WEAPON_PISTOL_DUAL, 9, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_PISTOL_DUAL, 11, ACT_VM_RELOAD_EMPTY_LAYER);
		// Add(NECOLA_WEAPON_PISTOL_DUAL, 13, ACT_VM_DRYFIRE);
		// Add(NECOLA_WEAPON_PISTOL_DUAL, 15, ACT_VM_DRYFIRE_LEFT);
		Add(NECOLA_WEAPON_PISTOL_DUAL, 19, ACT_VM_MELEE_LAYER);

		//magnum
		Add(NECOLA_WEAPON_DEAGLE, 3, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_DEAGLE, 5, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_DEAGLE, 7, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_DEAGLE, 9, ACT_VM_RELOAD_EMPTY_LAYER);
		// Add(NECOLA_WEAPON_DEAGLE, 11, ACT_VM_DRYFIRE);
		Add(NECOLA_WEAPON_DEAGLE, 13, ACT_VM_MELEE_LAYER);

		//smg
		Add(NECOLA_WEAPON_UZI, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_UZI, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_UZI, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_UZI, 10, ACT_VM_MELEE_LAYER);

		//silenced_smg
		Add(NECOLA_WEAPON_MAC10, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_MAC10, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MAC10, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_MAC10, 10, ACT_VM_MELEE_LAYER);

		//smg_mp5
		Add(NECOLA_WEAPON_MP5, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_MP5, 6, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_MP5, 8, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MP5, 10, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MP5, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MP5, 14, ACT_VM_MELEE_LAYER);

		//m16
		Add(NECOLA_WEAPON_M16A1, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_M16A1, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_M16A1, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_M16A1, 10, ACT_VM_MELEE_LAYER);

		//ak47
		Add(NECOLA_WEAPON_AK47, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_AK47, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_AK47, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_AK47, 10, ACT_VM_MELEE_LAYER);

		//scar
		Add(NECOLA_WEAPON_SCAR, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_SCAR, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SCAR, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_SCAR, 10, ACT_VM_MELEE_LAYER);

		//sg552
		Add(NECOLA_WEAPON_SSG552, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_SSG552, 6, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_SSG552, 8, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SSG552, 10, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SSG552, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SSG552, 14, ACT_VM_MELEE_LAYER);

		//pump
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 6, ACT_VM_RELOAD_LOOP_LAYER);
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 8, ACT_VM_RELOAD_END_LAYER);
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 10, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_PUMP_SHOTGUN, 14, ACT_VM_MELEE_LAYER);

		//chrome
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 6, ACT_VM_RELOAD_LOOP_LAYER);
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 8, ACT_VM_RELOAD_END_LAYER);
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 10, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_CHROME_SHOTGUN, 14, ACT_VM_MELEE_LAYER);

		//autoshotgun
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 6, ACT_VM_RELOAD_LOOP_LAYER);
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 8, ACT_VM_RELOAD_END_LAYER);
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 10, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_AUTO_SHOTGUN, 14, ACT_VM_MELEE_LAYER);

		//spas
		Add(NECOLA_WEAPON_SPAS, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_SPAS, 6, ACT_VM_RELOAD_LOOP_LAYER);
		Add(NECOLA_WEAPON_SPAS, 8, ACT_VM_RELOAD_END_LAYER);
		Add(NECOLA_WEAPON_SPAS, 10, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_SPAS, 12, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SPAS, 14, ACT_VM_MELEE_LAYER);

		//mini14
		Add(NECOLA_WEAPON_HUNTING_RIFLE, 9, ACT_VM_RELOAD_SNIPER_LAYER);
		Add(NECOLA_WEAPON_HUNTING_RIFLE, 19, ACT_VM_DEPLOY_SNIPER_LAYER);
		Add(NECOLA_WEAPON_HUNTING_RIFLE, 21, ACT_VM_SHOOT_SNIPER_LAYER);
		Add(NECOLA_WEAPON_HUNTING_RIFLE, 23, ACT_VM_MELEE_SNIPER_LAYER);

		//military
		Add(NECOLA_WEAPON_MILITARY_SNIPER, 3, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_MILITARY_SNIPER, 4, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MILITARY_SNIPER, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_MILITARY_SNIPER, 9, ACT_VM_MELEE_LAYER);

		//awp
		Add(NECOLA_WEAPON_AWP, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_AWP, 6, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_AWP, 8, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_AWP, 10, ACT_VM_MELEE_LAYER);

		//scout
		Add(NECOLA_WEAPON_SCOUT, 4, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_SCOUT, 6, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_SCOUT, 8, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_SCOUT, 10, ACT_VM_MELEE_LAYER);

		//m60
		Add(NECOLA_WEAPON_M60, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_M60, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_M60, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_M60, 10, ACT_VM_MELEE_LAYER);

		//grenade launcher
		Add(NECOLA_WEAPON_GRENADE_LAUNCHER, 4, ACT_VM_DEPLOY_LAYER);
		Add(NECOLA_WEAPON_GRENADE_LAUNCHER, 6, ACT_VM_PRIMARYATTACK_LAYER);
		Add(NECOLA_WEAPON_GRENADE_LAUNCHER, 8, ACT_VM_RELOAD_LAYER);
		Add(NECOLA_WEAPON_GRENADE_LAUNCHER, 10, ACT_VM_MELEE_LAYER);


		//bat
		Add(NECOLA_WEAPON_MELEE_BAT, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_BAT, 3, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_BAT, 5, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_BAT, 7, ACT_VM_HITRIGHT);
		Add(NECOLA_WEAPON_MELEE_BAT, 12, ACT_VM_SECONDARYATTACK_LAYER);

		//cricketbat
		Add(NECOLA_WEAPON_MELEE_CRICKETBAT, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_CRICKETBAT, 3, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_CRICKETBAT, 5, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_CRICKETBAT, 7, ACT_VM_HITRIGHT);
		Add(NECOLA_WEAPON_MELEE_CRICKETBAT, 12, ACT_VM_SECONDARYATTACK_LAYER);

		//crowbar
		Add(NECOLA_WEAPON_MELEE_CROWBAR, 3, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_CROWBAR, 5, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_CROWBAR, 6, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_CROWBAR, 9, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_CROWBAR, 11, ACT_VM_SECONDARYATTACK_LAYER);

		//guitar
		Add(NECOLA_WEAPON_MELEE_GUITAR, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 6, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 8, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 11, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_GUITAR, 16, ACT_VM_SECONDARYATTACK_LAYER);

		//fireaxe
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 6, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 8, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 11, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_FIREAXE, 16, ACT_VM_SECONDARYATTACK_LAYER);

		//pan
		Add(NECOLA_WEAPON_MELEE_PAN, 1, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_PAN, 5, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_PAN, 6, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_PAN, 9, ACT_VM_SECONDARYATTACK_LAYER);


		//golfclub
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 3, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 5, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 7, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_GOLFGLUB, 12, ACT_VM_SECONDARYATTACK_LAYER);

		//katana
		Add(NECOLA_WEAPON_MELEE_KATANA, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_KATANA, 3, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_KATANA, 5, ACT_VM_HITCENTER);
		Add(NECOLA_WEAPON_MELEE_KATANA, 7, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_KATANA, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_KATANA, 12, ACT_VM_SECONDARYATTACK_LAYER);

		//knife
		Add(NECOLA_WEAPON_MELEE_KNIFE, 3, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_KNIFE, 4, ACT_VM_HITRIGHT);
		Add(NECOLA_WEAPON_MELEE_KNIFE, 7, ACT_VM_SECONDARYATTACK_LAYER);

		//machete
		Add(NECOLA_WEAPON_MELEE_MACHETE, 0, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_MACHETE, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_MACHETE, 5, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_MACHETE, 7, ACT_VM_HITRIGHT);
		Add(NECOLA_WEAPON_MELEE_MACHETE, 12, ACT_VM_SECONDARYATTACK_LAYER);


		//pitchfork
		Add(NECOLA_WEAPON_MELEE_PITCHFORK, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_PITCHFORK, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_PITCHFORK, 5, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_PITCHFORK, 7, ACT_VM_HITRIGHT);
		Add(NECOLA_WEAPON_MELEE_PITCHFORK, 10, ACT_VM_SECONDARYATTACK_LAYER);

		//shield
		Add(NECOLA_WEAPON_MELEE_SHIELD, 1, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 3, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 5, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 7, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 8, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 10, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_SHIELD, 15, ACT_VM_SECONDARYATTACK_LAYER);

		//shovel
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 6, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 7, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_SHOVEL, 12, ACT_VM_SECONDARYATTACK_LAYER);

		//tonfa
		Add(NECOLA_WEAPON_MELEE_TONFA, 2, ACT_VM_DRAW);
		Add(NECOLA_WEAPON_MELEE_TONFA, 4, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_TONFA, 6, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_TONFA, 8, ACT_VM_SHOOT_LAYER);
		Add(NECOLA_WEAPON_MELEE_TONFA, 9, ACT_VM_HITLEFT);
		Add(NECOLA_WEAPON_MELEE_TONFA, 12, ACT_VM_SECONDARYATTACK_LAYER);
		Add(NECOLA_WEAPON_MELEE_TONFA, 14, ACT_VM_SECONDARYATTACK_LAYER);

	}
};

namespace G { inline DefaultViewModelSequence SequenceStore; }
